name: Build and Push Docker Image with Custom Branch Tags

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 提取分支名称和提交哈希
      - name: Extract branch name and commit hash
        id: vars
        run: |
          REPO_NAME=toolbox
          BRANCH_NAME=${GITHUB_REF_NAME} # 更直接的分支名称
          SHORT_HASH=$(git rev-parse --short HEAD)
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${REPO_NAME}-${BRANCH_NAME}
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "SHORT_HASH=${SHORT_HASH}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      # 登录到 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${IMAGE_NAME}:${SHORT_HASH} -t ${IMAGE_NAME}:latest .

      # 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${IMAGE_NAME}:${SHORT_HASH}
          docker push ${IMAGE_NAME}:latest
